server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7lle2ugvqtc73f6tl6g-a/portfolio_db_2dcr
spring.datasource.username=portfolio_db_2dcr_user
spring.datasource.password=GYQIW8xoWlIEPdY8jqrOHZQIic7wfAOu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=myPortfolioSecretKey1234567890abcdef
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhiraendra200545@gmail.com
spring.mail.password=vwci yvgp kyny vjvo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
portfolio.email.to=dhiraendra200545@gmail.com
