server.port=${PORT:8080}

SPRING_DATASOURCE_URL        = jdbc:mysql://roundhouse.proxy.rlwy.net:43331/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
SPRING_DATASOURCE_USERNAME   = root
SPRING_DATASOURCE_PASSWORD   = abilSBJkXTyiryTGIIaZoKtPMnryTjpT
SPRING_JPA_HIBERNATE_DDL_AUTO = update
SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT = org.hibernate.dialect.MySQLDialect
JWT_SECRET                   = mySecretKey1234567890abcdefghijklmn
JWT_EXPIRATION               = 86400000
SPRING_MAIL_HOST             = smtp.gmail.com
SPRING_MAIL_PORT             = 587
SPRING_MAIL_USERNAME         = dhiraendra200545@gmail.com
SPRING_MAIL_PASSWORD         = vwci yvgp kyny vjvo
SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH = true
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE = true
PORTFOLIO_EMAIL_TO           = dhiraendra200545@gmail.com